sudo: required

before_install:
  - curl -fsSL https://experimental.docker.com/ | sudo sh
  - curl -L https://github.com/docker/compose/releases/download/1.8.0-rc2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
script:
  - (cd docker && ./up.sh --init-only && sudo docker-compose up -d)
  - bash -c 'while sleep 300; echo "heartbeat for travis 10min limit"; done' &
  - sudo docker exec -it jepsen-control bash -c 'cd /jepsen/etcd; lein test'
